{{- if not .Values.credentialsSecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "karpenter.credentialsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  DIGITALOCEAN_TOKEN: {{ required "apiToken is required (DigitalOcean PAT with read and write)" .Values.apiToken | quote }}
{{- end }}
